# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: true

serversTransport:
  rootCAs:
    - foo.crt
    - bar.crt

entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :8081
# providers:
#   # Enable the file provider to define routers / middlewares / services in file
#   file:
#     directory: /path/to/dynamic/conf
